### ISSUE TITLE
Gem not available from rubygems.org

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [warmfusion/sensu-extension-snmptrap#3]
Hello!

I wanted to try this extension -- we have a fair number of things using traps to report problems -- but could not find it on rubygems.org.

Is the project alive? Is there a problem with the gem? Please, advise. Thank you!

**Comment by warmfusion** [comment]
The biggest problem i've had with this extension is the delivery into Sensu itself.

I made some changes (in a branch) to make it work like a normal plugin, but apparently [the only way to load extensions is through symlink](https://twitter.com/portertech/status/735584856671817728)

I'll make the necessary changes to make it into a proper gem and get it published.

**Comment by warmfusion** [comment]
ok, its published into Rubygems.org

https://rubygems.org/gems/sensu-plugins-snmptrap-extension

gem install sensu-plugins-snmptrap-extension

However, there are additional steps to getting it into sensu, and I still need to get some of the core components operational.

Consider the code to be alpha for the time being. :boom:

Patches welcome :-)

**Comment by warmfusion** [comment]
Howdy.

I've got what I believe to be a working version now avaliable on rubygems for use.

Give it a go and let me know if you have any problems.
